import type { CollegiumDomainSnapshot } from "./collegium-domain.ts";

export function buildDefaultCollegiumDomainSnapshot(): CollegiumDomainSnapshot {
  return {
    generatedAt: "2026-03-09T12:00:00.000Z",
    pilots: [
      {
        id: "pilot-ana",
        displayName: "Ana Cruz",
        status: "active",
        reputationScore: 92,
        productionUnitsValidated: 7,
        networkNodeId: "network-alpha",
        activeMobilityEvents: 1,
        flags: [],
      },
      {
        id: "pilot-bruno",
        displayName: "Bruno Vale",
        status: "restricted",
        reputationScore: 71,
        productionUnitsValidated: 0,
        networkNodeId: "network-alpha",
        activeMobilityEvents: 0,
        flags: ["identity_review"],
      },
      {
        id: "pilot-clara",
        displayName: "Clara Mota",
        status: "active",
        reputationScore: 88,
        productionUnitsValidated: 5,
        networkNodeId: "network-beta",
        activeMobilityEvents: 1,
        flags: ["route_dispute_watch"],
      },
    ],
    passengers: [
      {
        id: "passenger-lia",
        displayName: "Lia Santos",
        status: "active",
        reputationScore: 90,
        trustFlags: [],
        completedTrips: 12,
      },
      {
        id: "passenger-noah",
        displayName: "Noah Lima",
        status: "flagged",
        reputationScore: 64,
        trustFlags: ["payment_dispute"],
        completedTrips: 5,
      },
      {
        id: "passenger-iris",
        displayName: "Iris Costa",
        status: "active",
        reputationScore: 87,
        trustFlags: [],
        completedTrips: 8,
      },
    ],
    mobilityEvents: [
      {
        id: "mob-1001",
        pilotId: "pilot-ana",
        passengerId: "passenger-lia",
        status: "completed",
        startedAt: "2026-03-09T09:00:00.000Z",
        completedAt: "2026-03-09T09:32:00.000Z",
        productionUnitsGenerated: 4,
        routeLabel: "Centro -> Aeroporto",
        riskSignals: [],
        evidenceRefs: ["trip:mob-1001", "gps:mob-1001"],
      },
      {
        id: "mob-1002",
        pilotId: "pilot-clara",
        passengerId: "passenger-noah",
        status: "contested",
        startedAt: "2026-03-09T10:10:00.000Z",
        completedAt: "2026-03-09T10:44:00.000Z",
        productionUnitsGenerated: 3,
        routeLabel: "Hospital -> Zona Sul",
        riskSignals: ["passenger_dispute", "route_variance"],
        evidenceRefs: ["trip:mob-1002", "support:ticket-204"],
      },
      {
        id: "mob-1003",
        pilotId: "pilot-ana",
        passengerId: "passenger-iris",
        status: "in_progress",
        startedAt: "2026-03-09T11:20:00.000Z",
        productionUnitsGenerated: 0,
        routeLabel: "Rodoviaria -> Centro",
        riskSignals: [],
        evidenceRefs: ["trip:mob-1003"],
      },
      {
        id: "mob-1004",
        pilotId: "pilot-clara",
        passengerId: "passenger-lia",
        status: "completed",
        startedAt: "2026-03-09T08:05:00.000Z",
        completedAt: "2026-03-09T08:31:00.000Z",
        productionUnitsGenerated: 5,
        routeLabel: "Terminal Norte -> Centro",
        riskSignals: ["surge_load"],
        evidenceRefs: ["trip:mob-1004", "gps:mob-1004"],
      },
    ],
    productionLedger: [
      {
        mobilityEventId: "mob-1001",
        pilotId: "pilot-ana",
        amount: 4,
        validatedAt: "2026-03-09T09:35:00.000Z",
        evidenceRefs: ["trip:mob-1001", "ledger:pu-1001"],
      },
      {
        mobilityEventId: "mob-1002",
        pilotId: "pilot-clara",
        amount: 3,
        validatedAt: "2026-03-09T10:46:00.000Z",
        evidenceRefs: ["trip:mob-1002", "ledger:pu-1002"],
      },
      {
        mobilityEventId: "mob-1004",
        pilotId: "pilot-clara",
        amount: 2,
        validatedAt: "2026-03-09T08:33:00.000Z",
        evidenceRefs: ["trip:mob-1004", "ledger:pu-1003"],
      },
      {
        mobilityEventId: "mob-1004",
        pilotId: "pilot-ana",
        amount: 3,
        validatedAt: "2026-03-09T08:34:00.000Z",
        evidenceRefs: ["network:supervision-alpha", "ledger:pu-1004"],
      },
    ],
    networkNodes: [
      {
        id: "network-alpha",
        label: "Alpha Corridor",
        pilotIds: ["pilot-ana", "pilot-bruno"],
        supervisedBy: "pilot-ana",
        activeProductionUnits: 9,
      },
      {
        id: "network-beta",
        label: "Beta Reach",
        pilotIds: ["pilot-clara"],
        supervisedBy: "pilot-clara",
        activeProductionUnits: 5,
      },
    ],
    deliberations: [
      {
        id: "delib-301",
        title: "Resolve Bruno restriction before demand surge",
        status: "pending_chairman",
        linkedMobilityEventIds: ["mob-1002"],
        linkedPilotIds: ["pilot-bruno"],
        riskLevel: "high",
        summary:
          "Restriction on Bruno Vale limits corridor coverage and requires Chairman review before releasing new demand windows.",
        options: [
          "Maintain restriction until identity review closes",
          "Release under supervised corridor access",
          "Escalate to manual legal review",
        ],
        recommendedPath: "Release under supervised corridor access after legal sign-off.",
        chairmanActionRequired: true,
        evidenceRefs: ["support:ticket-204", "risk:pilot-bruno"],
      },
      {
        id: "delib-302",
        title: "Contest route variance on mob-1002",
        status: "under_review",
        linkedMobilityEventIds: ["mob-1002"],
        linkedPilotIds: ["pilot-clara"],
        riskLevel: "medium",
        summary:
          "The contested mobility event needs protocol review to decide compensation and passenger trust adjustments.",
        options: [
          "Compensate passenger and preserve pilot score",
          "Split liability between pilot and passenger",
        ],
        recommendedPath:
          "Compensate passenger while preserving pilot eligibility pending final evidence review.",
        chairmanActionRequired: false,
        evidenceRefs: ["trip:mob-1002", "support:ticket-204"],
      },
    ],
  };
}
